[
  {
    "name": "work",
    "before_text": "Go to a work",
    "after_text": "Work! Work! Work!",
    "conds": [
      { 
        "field":"mana",
        "operator":"<",
        "value":50 },
      { 
        "field":"fatigue",
        "operator":"<",
        "value":10}],
    "effects": [
      {
        "field":"cheerfulness",
        "operator":"-",
        "value":5 },
      {
        "field":"mana",
        "operator":"-",
        "value":30},
      {
        "field":"money",
        "operator":"+",
        "value":150},
      {
        "field":"fatigue",
        "operator":"+",
        "value":70}]
  },
  {
    "name": "behold",
    "before_text": "Behold nature",
    "after_text": "Medication for the melancholy",
    "conds": [],
    "effects": [
      {
        "field":"cheerfulness",
        "operator":"+",
        "value":1 },
      {
        "field":"mana",
        "operator":"-",
        "value":10},
      {
        "field":"fatigue",
        "operator":"+",
        "value":10}]
  },
  {
    "name": "wine",
    "before_text": "Drink wine and watch TV serial",
    "after_text": "In vino veritas",
    "conds": [
      { 
        "field":"money",
        "operator":">",
        "value":20 },
      { 
        "field":"cheerfulness",
        "operator":">",
        "value":1}],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"-",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":30},
      {
        "field":"fatigue",
        "operator":"+",
        "value":10},
      {
        "field":"health",
        "operator":"-",
        "value":5},
      { 
        "field":"money",
        "operator":"-",
        "value":20 }]
  },
  {
    "name": "bar",
    "before_text": "Go to the bar",
    "after_text": "Up all night with Kerry King. I got to tell ya poker's his thing.",
    "conds": [
      { 
        "field":"money",
        "operator":">",
        "value":100 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":60},
      {
        "field":"fatigue",
        "operator":"+",
        "value":40},
      {
        "field":"health",
        "operator":"-",
        "value":10},
      { 
        "field":"money",
        "operator":"-",
        "value":100 }]
  },
  {
    "name": "marginal",
    "before_text": "Drink with marginals",
    "after_text": "I'm a intellectual in the third generation",
    "conds": [
      { 
        "field":"money",
        "operator":">",
        "value":150 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":5},
      {
        "field":"mana",
        "operator":"+",
        "value":90},
      {
        "field":"fatigue",
        "operator":"+",
        "value":80},
      {
        "field":"health",
        "operator":"-",
        "value":80},
      { 
        "field":"money",
        "operator":"-",
        "value":150 }]
  },
  {
    "name": "sing1",
    "before_text": "Sing to the subway",
    "after_text": "This is my favourite song",
    "conds": [
      { 
        "field":"mana",
        "operator":"<=",
        "value":40 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":10},
      {
        "field":"fatigue",
        "operator":"+",
        "value":20},
      { 
        "field":"money",
        "operator":"+",
        "value":10 }]
  },
  {
    "name": "sing2",
    "before_text": "Sing to the subway",
    "after_text": "This is my favourite song",
    "conds": [
      { 
        "field":"mana",
        "operator":">=",
        "value":70 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":10},
      {
        "field":"fatigue",
        "operator":"+",
        "value":20},
      { 
        "field":"money",
        "operator":"+",
        "value":10 }]
  },
  {
    "name": "sing3",
    "before_text": "Sing to the subway",
    "after_text": "This is my favourite song",
    "conds": [
      { 
        "field":"mana",
        "operator":">",
        "value":40 },
      { 
        "field":"mana",
        "operator":"<",
        "value":70 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":10},
      {
        "field":"fatigue",
        "operator":"+",
        "value":20},
      { 
        "field":"money",
        "operator":"+",
        "value":60 }]
  },
  {
    "name": "sleep1",
    "before_text": "Go to bed",
    "after_text": "Let there be night",
    "conds": [
      { 
        "field":"mana",
        "operator":"<=",
        "value":30 }],
    "effects": [
      {
        "field":"health",
        "operator":"+",
        "value":90},
      {
        "field":"mana",
        "operator":"-",
        "value":10},
      {
        "field":"fatigue",
        "operator":"-",
        "value":70}]
  },
  {
    "name": "sleep2",
    "before_text": "Go to bed",
    "after_text": "Let there be night",
    "conds": [
      { 
        "field":"mana",
        "operator":">=",
        "value":70 }],
    "effects": [
      {
        "field":"cheerfulness",
        "operator":"-",
        "value":3},
      {
        "field":"mana",
        "operator":"-",
        "value":10},
      {
        "field":"fatigue",
        "operator":"-",
        "value":70}]
  },
  {
    "name": "sleep3",
    "before_text": "Go to bed",
    "after_text": "Let there be night",
    "conds": [
      { 
        "field":"mana",
        "operator":">",
        "value":30 },
      { 
        "field":"mana",
        "operator":"<",
        "value":70 }],
    "effects": [
      {
        "field":"mana",
        "operator":"-",
        "value":10},
      {
        "field":"fatigue",
        "operator":"-",
        "value":70}]
  }
]
