[
  {
    "name": "work",
    "before_text": "Пойти работать",
    "after_text": "Работать, афроамериканец! Солнце еще высоко!",
    "conds": [
      { 
        "field":"mana",
        "operator":"<",
        "value":50 },
      { 
        "field":"fatigue",
        "operator":"<",
        "value":10}],
    "effects": [
      {
        "field":"cheerfulness",
        "operator":"-",
        "value":5 },
      {
        "field":"mana",
        "operator":"-",
        "value":30},
      {
        "field":"money",
        "operator":"+",
        "value":150},
      {
        "field":"fatigue",
        "operator":"+",
        "value":70}]
  },
  {
    "name": "behold",
    "before_text": "Созерцать природу",
    "after_text": "Слава, роскошный вид! и тогда восславь солнце!",
    "conds": [],
    "effects": [
      {
        "field":"cheerfulness",
        "operator":"+",
        "value":1 },
      {
        "field":"mana",
        "operator":"-",
        "value":10},
      {
        "field":"fatigue",
        "operator":"+",
        "value":10}]
  },
  {
    "name": "wine",
    "before_text": "Пить вино и смотреть сериалы",
    "after_text": "In vino veritas!",
    "conds": [
      { 
        "field":"money",
        "operator":">",
        "value":20 },
      { 
        "field":"cheerfulness",
        "operator":">",
        "value":1}],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"-",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":30},
      {
        "field":"fatigue",
        "operator":"+",
        "value":10},
      {
        "field":"health",
        "operator":"-",
        "value":5},
      { 
        "field":"money",
        "operator":"-",
        "value":20 }]
  },
  {
    "name": "bar",
    "before_text": "Пойти в бар",
    "after_text": "Заходят в бар француз, американец и Валера...",
    "conds": [
      { 
        "field":"money",
        "operator":">",
        "value":100 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":60},
      {
        "field":"fatigue",
        "operator":"+",
        "value":40},
      {
        "field":"health",
        "operator":"-",
        "value":10},
      { 
        "field":"money",
        "operator":"-",
        "value":100 }]
  },
  {
    "name": "marginal",
    "before_text": "Выпить с маргиналами",
    "after_text": "Я в трёх поколениях интеллигент!",
    "conds": [
      { 
        "field":"money",
        "operator":">",
        "value":150 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":5},
      {
        "field":"mana",
        "operator":"+",
        "value":90},
      {
        "field":"fatigue",
        "operator":"+",
        "value":80},
      {
        "field":"health",
        "operator":"-",
        "value":80},
      { 
        "field":"money",
        "operator":"-",
        "value":150 }]
  },
  {
    "name": "sing1",
    "before_text": "Петь в переходе",
    "after_text": "Чёрный вооороон, что кружишься...",
    "conds": [
      { 
        "field":"mana",
        "operator":"<=",
        "value":40 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":10},
      {
        "field":"fatigue",
        "operator":"+",
        "value":20},
      { 
        "field":"money",
        "operator":"+",
        "value":10 }]
  },
  {
    "name": "sing2",
    "before_text": "Петь в переходе",
    "after_text": "Чёрный вооороон, что кружишься...",
    "conds": [
      { 
        "field":"mana",
        "operator":">=",
        "value":70 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":10},
      {
        "field":"fatigue",
        "operator":"+",
        "value":20},
      { 
        "field":"money",
        "operator":"+",
        "value":10 }]
  },
  {
    "name": "sing3",
    "before_text": "Петь в переходе",
    "after_text": "Чёрный вооороон, что кружишься...",
    "conds": [
      { 
        "field":"mana",
        "operator":">",
        "value":40 },
      { 
        "field":"mana",
        "operator":"<",
        "value":70 }],
    "effects": [
      { 
        "field":"cheerfulness",
        "operator":"+",
        "value":1},
      {
        "field":"mana",
        "operator":"+",
        "value":10},
      {
        "field":"fatigue",
        "operator":"+",
        "value":20},
      { 
        "field":"money",
        "operator":"+",
        "value":60 }]
  },
  {
    "name": "sleep1",
    "before_text": "Спать",
    "after_text": "Утро вечера...бодунее.",
    "conds": [
      { 
        "field":"mana",
        "operator":"<=",
        "value":30 }],
    "effects": [
      {
        "field":"health",
        "operator":"+",
        "value":90},
      {
        "field":"mana",
        "operator":"-",
        "value":10},
      {
        "field":"fatigue",
        "operator":"-",
        "value":70}]
  },
  {
    "name": "sleep2",
    "before_text": "Спать",
    "after_text": "Утро вечера...бодунее.",
    "conds": [
      { 
        "field":"mana",
        "operator":">=",
        "value":70 }],
    "effects": [
      {
        "field":"cheerfulness",
        "operator":"-",
        "value":3},
      {
        "field":"mana",
        "operator":"-",
        "value":10},
      {
        "field":"fatigue",
        "operator":"-",
        "value":70}]
  },
  {
    "name": "sleep3",
    "before_text": "Спать",
    "after_text": "Утро вечера...бодунее.",
    "conds": [
      { 
        "field":"mana",
        "operator":">",
        "value":30 },
      { 
        "field":"mana",
        "operator":"<",
        "value":70 }],
    "effects": [
      {
        "field":"mana",
        "operator":"-",
        "value":10},
      {
        "field":"fatigue",
        "operator":"-",
        "value":70}]
  },



  {
    "name": "suicide",
    "before_text": "Выйти в окно",
    "after_text": "Разбежавшись, прыгну со скалыыы!..",
    "conds": [],
    "effects": [
      {
        "field":"health",
        "operator":"-",
        "value":9000}]
  },
  {
    "name": "fight1",
    "before_text": "Пьяная драка",
    "after_text": "Где тут дрын какой-нибудь?!",
    "conds": [
      { 
        "field":"mana",
        "operator":">",
        "value":50 },
      { 
        "field":"mana",
        "operator":"<",
        "value":75 }],
    "effects": [
      {
        "field":"health",
        "operator":"-",
        "value":10},
      {
        "field":"mana",
        "operator":"-",
        "value":25},
      {
        "field":"cheerfulness",
        "operator":"+",
        "value":15},
      {
        "field":"fatigue",
        "operator":"+",
        "value":25},
      {
        "field":"money",
        "operator":"+",
        "value":10}
    ]
  },
  {
    "name": "fight2",
    "before_text": "Пьяная драка",
    "after_text": "Где тут дрын какой-нибудь?!",
    "conds": [
      { 
        "field":"mana",
        "operator":">",
        "value":74 }
      ],
    "effects": [
      {
        "field":"health",
        "operator":"-",
        "value":5},
      {
        "field":"mana",
        "operator":"-",
        "value":50},
      {
        "field":"cheerfulness",
        "operator":"+",
        "value":25},
      {
        "field":"fatigue",
        "operator":"+",
        "value":25},
      {
        "field":"money",
        "operator":"+",
        "value":25}
    ]
  }
]
